lab_project/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls'))
]

todo/urls.py
from django.urls import path
from .views import list,show_details,delete_task,add_task,edit_task
app_name='todo'
urlpatterns = [
    path('tasks/', list,name='list'),
    path('tasks/add',add_task, name='add_task'),
    path('tasks/<id>',show_details,name='show_details'),
    path('tasks/delete/<id>',delete_task,name='delete_task'),
    path('tasks/edit/<id>',edit_task,name='edit_task')

]
#
#

todo/models.py
from django.db import models

# Create your models here.

todo/forms.py
from  django import forms
class task_form(forms.Form):
    id=forms.CharField()
    name=forms.CharField()
    is_done=forms.ChoiceField(choices=[('true','True'),('false','False')])
    description=forms.CharField(widget=forms.Textarea)

todo/views.py
from django.shortcuts import render,HttpResponse
from .forms import task_form
my_list=[
    {
        'id':1,
        'name':'breakfast',
        'is_done':False,
        'description':'to eat your first meal'
    },
    {
        'id':2,
        'name':'attend lecture',
        'is_done':False,
        'description':'to attend the lecture '
    },
    {
        'id':3,
        'name':'make lab',
        'is_done':False,
        'description':'to make the lab '
    },
    {
        'id':4,
        'name':'launch',
        'is_done':False,
        'description':'to eat your second meal '
    }


]


def list(request):

    return render(request,'todo/home.html',context={'todo_list':my_list})

def show_details(request ,**kwargs):
    # print(kwargs.get('id'))
    id=int(kwargs.get('id'))
    task=my_list[id-1]


    return render(request,'todo/details.html',context={'task':task})
def delete_task(request,**kwargs):

    id = int(kwargs.get('id'))
    if(my_list[id-1].get('is_done')):

        my_list.pop(id-1)
        return list(request)
    else:
        return render(request,'todo/home.html',{'todo_list':my_list,'warning':'task cant be deleted unless it is done'})


# def render_form(request,**kwargs):
#     if(kwargs):
#         id = int(kwargs.get('id'))
#         task = my_list[id - 1]
#         return  render(request,'todo/todo_form.html',context={'task':task,'bool':True})
#     else:
#         return render(request, 'todo/todo_form.html', context={'bool': False})

def render_form(request,**kwargs):
    print('O7EHA')

def add_task(request):
    if request.method == 'POST':  # If the form has been submitted...
        form = task_form(request.POST)  # A form bound to the POST data
        if form.is_valid():
            task={
            'id':form.cleaned_data['id'],
            'name' : form.cleaned_data['name'],
            'is_done': form.cleaned_data['is_done'],
            'description' : form.cleaned_data['description']
            }
            my_list.append(task)
            return list(request)

    form = task_form()
    return render(request, 'todo/task_form.html', {'form': form})


def edit_task(request,**kwargs):
    if request.method == 'POST':  # If the form has been submitted...
        form = task_form(request.POST)  # A form bound to the POST data
        if form.is_valid():
            task={
            'id':form.cleaned_data['id'],
            'name' : form.cleaned_data['name'],
            'is_done': form.cleaned_data['is_done'],
            'description' : form.cleaned_data['description']
            }
            id = int(kwargs.get('id'))
            my_list[id - 1]=task
            return list(request)

    form = task_form()
    return render(request, 'todo/task_form.html', {'form': form})

todo/templates/todo/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}  {% endblock  %}</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<div class="container">
{% block content %}  {% endblock  %}
</div>
</body>
</html>

todo/templates/todo/details.html
{% extends 'todo/base.html'%}
{%block title%}todo-details{%endblock%}
{% block content%}
<div class="card" ">
  <div class="card-header">
    Name : {{task.name|title}}
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">id : {{task.id}}</li>
    <li class="list-group-item">is_done : {{task.is_done}}</li>
    <li class="list-group-item">description : {{task.description}}</li>
  </ul>
</div>
{%endblock%}

todo/templates/todo/home.html
{% extends 'todo/base.html'%}
{%block title%}todo-home{%endblock%}
{% block content %}
{%if warning%}
<div class="bg-danger">
    {{warning}}
</div>
{%endif%}
<table class="table table-bordered table-striped my-5">
  <thead>
  <th>id</th>
   <th>task</th>
   <th>is_done</th>
   <th>description</th>
   <th>...</th>
  </thead>
    <tbody>

    {%for task in todo_list%}
    <tr>
        <td>{{task.id}}</td>
        <td>{{task.name|title}}</td>
        <td>{{task.is_done}}</td>
        <td>{{task.description}}</td>
        <td>
            <a href="{% url 'todo:show_details' task.id %}" class="btn btn-secondary">view</a>
            <a href="{% url 'todo:delete_task' task.id %}" class="btn btn-danger">delete</a>
            <a href="{% url 'todo:edit_task' task.id %}" class="btn btn-primary">edit</a>
        </td>
    </tr>
     {%endfor%}
    </tbody>
</table>

<a href="{% url 'todo:add_task' %}" class="btn btn-success" >add task</a>
{%endblock%}

todo/templates/todo/task_form.html
{% extends 'todo/base.html'%}
{%block title%}todo-form{%endblock%}
{%block content%}
<form method="post">
    {% csrf_token %}
{{form}}
    <button class="btn btn-success">add</button>
</form>

{%endblock%}

todo/templates/todo/todo_form.html
{% extends 'todo/base.html'%}
{%block title%}todo-form{%endblock%}
{%block content%}
{% if bool%}
<form method="post" onsubmit="{%url 'todo:add_task'%}">
    {% csrf_token %}
    <span>task id :</span>
<input name="id" value="{{task.id}}">
<span>task name :</span>
<input name="name" value="{{task.name}}">
<span>is done :</span>

    <select name="is_done" value="{{task.is_done}}">
        {%if task.is_done%}
        <option>True</option>
        <option>False</option>
        {%else%}
        <option>False</option>
        <option>True</option>
        {%endif%}
    </select>

<span>task description :</span>
<input class="description" value="{{task.description}}">
<button type="submit" class="btn btn-success">save</button>
</form>
{%else%}
<form method="post">
    <span>task id :</span>
<input name="id">
<span>task name :</span>
<input name="name">
<span>is done :</span>

    <select name="is_done" id="">
        <option>True</option>
        <option>False</option>
    </select>

<span>task description :</span>
<input class="description">
<button type="submit" class="btn btn-success">add</button>
</form>
{%endif%}

{%endblock%}